### PR TITLE
75% of german translations by thomas

### PR DESCRIPTION
**Pull request by Molkenbur**

### CODE REVIEW

**Comment by simonmorley** [comment]
Question: "20 minute, quickcode" --> "20 Minuten gültig"

Valid for 20 minutes?

**Comment by Molkenbur** [comment]
Yes. Did I missunderstand this? All the different vouchers have to be checked anyway. It's still a bit abstract for me.

**Comment by simonmorley** [comment]
Let me see where that comment sits first. I think it's misleading in DE and EN

**Comment by Molkenbur** [comment]
OK. But I think that the translations are as good as possible today. When we test the site in german, there will be a lot of corrections. So don't delay the process for just a few wrong or dubious translations, please.

**Comment by simonmorley** [comment]
I've created a note about this for attention later.

Naming it 'valid for 20 minutes' isn't correct and will interfere with the description.

**Pull request merged**
