### PR TITLE
location name limit in sidebar menu

### PR DESCRIPTION
**Pull request by ariandora**

### CODE REVIEW

**Comment by simonmorley** [comment]
@ariandora Does this fix an issue?

**Comment by ariandora** [comment]
@simonmorley it's in jira, not in github

**Comment by simonmorley** [comment]
Can you summarise the issue so we know what it's fixes. Better still. Put
the issue in git.


On 4 Oct 2016, at 10:50, ariandora <notifications@github.com> wrote:

@simonmorley <https://github.com/simonmorley> it's in jira, not in github

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cucumber-tony/cucumber-frontend/pull/339#issuecomment-251411159>,
or mute the thread

**Comment by ariandora** [comment]
Created the bug -#342, closing this pull req, will change the behaviour to what we discussed

**Pull request closed without merging**
