### PR TITLE
Update de_DE.po (50%)

### PR DESCRIPTION
**Pull request by Molkenbur**
approx. 50% of all terms translated into german

### CODE REVIEW

**Comment by simonmorley** [comment]
I will resolve the merge conflicts in the am

**Comment by Molkenbur** [comment]
Hi Simon, I reverted my last change, merged the file with the latest CT/beta version and commited it again. The conflicts are gone now.

**Comment by simonmorley** [comment]
I've still got conflicts sadly.

**Comment by simonmorley** [comment]
Actually couldn't see any conflicts when I merged....

**Pull request merged**
