### PR TITLE
self-destructing networks

### PR DESCRIPTION
**Pull request by ewansheldon**
https://cucumber.atlassian.net/browse/CTBACK-221

### CODE REVIEW

**Comment by ewansheldon** [comment]
screen shot 2017-03-23 at 17 07 24
screen shot 2017-03-23 at 17 07 40

**Comment by ewansheldon** [comment]
screen shot 2017-03-23 at 17 09 55

**Comment by simonmorley** [comment]
@ewansheldon Let's merge to beta and test but the styling needs some work. Also, do the list of networks show the ttl??

**Comment by ewansheldon** [comment]
do you mean it should be displayed in the index table @simonmorley ? or just returned with the index json?

at the moment only with the show and displayed at the top of the show view as above

**Pull request merged**
