### PR TITLE
Update German and add French translations

### PR DESCRIPTION
**Pull request by Molkenbur**

### CODE REVIEW

**Comment by simonmorley** [comment]
@Molkenbur The French translations are a problem for us since they were completed by Google translate. And not a real human. 

We need them validated properly before they're merged.

**Comment by Molkenbur** [comment]
But they were reviewed and corrected by a real human.

**Comment by simonmorley** [comment]
What about the other 75%. Seriously, I'm not going to accept Google translate as a decent option here.

**Comment by Molkenbur** [comment]
We reviewed all and it is good enough for us. It's your decision.

**Comment by simonmorley** [comment]
For other languages we're insisting on two contributors. I'll get a student or something to do the French.

**Comment by simonmorley** [comment]
I'm going to merge this in but NOT provide the FR option until we've had them verified.

**Pull request merged**
