### PR TITLE
Ctback 221 self destructing networks

### PR DESCRIPTION
**Pull request by ewansheldon**
transitions still need work and needs to be made mobile-friendly but vastly improves the layout, especially for those who only want to create a regular permanent network

### CODE REVIEW

**Comment by simonmorley** [comment]
Ok, I will leave this for time being as I have other things to merge.

**Comment by simonmorley** [comment]
@ewansheldon can we have some screenshots in here pls.

**Comment by ewansheldon** [comment]
screen shot 2017-04-27 at 17 06 00
create button becomes next when self-destruct is active
screen shot 2017-04-27 at 17 06 06
which takes you to a page to let you select time
screen shot 2017-04-27 at 17 06 13

**Comment by ewansheldon** [comment]
☺️

**Comment by simonmorley** [comment]
@ZakMooney @ewansheldon Is this good to merge then??

**Comment by ewansheldon** [comment]
👍

**Comment by simonmorley** [comment]
@ZakMooney kindly check it looks amazing

**Pull request merged**
